In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
np.set_printoptions(threshold=sys.maxsize)

In [2]:
dataset=pd.read_csv('winequality-red.csv')
X=dataset.iloc[:,:-1].values
y1=dataset.iloc[:,-1]
y=dataset.iloc[:,-1].values

In [3]:
print(y1.unique())

[5 6 7 4 8 3]


In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3, random_state=0)

In [16]:
# print(len(y_test))

In [6]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train = sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [7]:
from sklearn.linear_model import LogisticRegression
softReg = LogisticRegression(multi_class = 'multinomial', solver = 'lbfgs')
softReg.fit(X_train , y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='multinomial', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [8]:
print(softReg.predict(sc.transform([[1.08000e+01, 4.70000e-01 ,4.30000e-01, 2.10000e+00 ,1.71000e-01 ,2.70000e+01
 , 6.60000e+01, 9.98200e-01, 3.17000e+00, 7.60000e-01, 1.08000e+01]])))

[6]


In [15]:
y_pred=softReg.predict(X_test)
# print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

In [13]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)


[[  0   0   3   0   0   0]
 [  0   0   9   5   1   0]
 [  0   0 157  50   1   0]
 [  0   0  58 125  21   0]
 [  0   0   3  26  16   0]
 [  0   0   0   3   2   0]]


In [12]:
print("accuracy:",softReg.score(X_test, y_test))

accuracy: 0.6208333333333333
