In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sys
np.set_printoptions(threshold=sys.maxsize)

In [3]:
dataset=pd.read_csv('winequality-red.csv')
X=dataset.iloc[:,:-1].values
y1=dataset.iloc[:,-1]
y=dataset.iloc[:,-1].values

In [4]:
print(y1.unique())

[5 6 7 4 8 3]


In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3, random_state=0)

In [6]:
print(len(y_test))

480


In [7]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train = sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [8]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0)
classifier.fit(X_train , y_train)

C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=0, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [9]:
# print(X_train)

In [10]:
print(classifier.predict(sc.transform([[1.08000e+01, 4.70000e-01 ,4.30000e-01, 2.10000e+00 ,1.71000e-01 ,2.70000e+01
 , 6.60000e+01, 9.98200e-01, 3.17000e+00, 7.60000e-01, 1.08000e+01]])))

[6]


In [11]:
y_pred=classifier.predict(X_test)
print(len(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1)))

480


In [12]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_pred, y_test)
print(cm)


[[  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  3  10 165  62   3   0]
 [  0   3  42 124  29   3]
 [  0   2   1  18  13   2]
 [  0   0   0   0   0   0]]


In [ ]:
print("accuracy:",classifier.score(X_test, y_test))